-- ============================================================================
-- SCRIPT DE SINCRONIZACIÓN DE PERMISOS, ROLES, SECCIONES Y ACCIONES (LIGHTSAIL)
-- ============================================================================
BEGIN;

-- 1. Asegurar columnas en caso de migraciones pendientes
ALTER TABLE IF EXISTS app_sections ADD COLUMN IF NOT EXISTS path VARCHAR;
ALTER TABLE IF EXISTS permissions ADD COLUMN IF NOT EXISTS target_section VARCHAR;

-- 2. TABLA ROLES
INSERT INTO roles (id, code, name, label, description, level, badge_color, permissions, created_at) VALUES (1, 'root', 'ROOT', 'SuperAdmin Programador', 'Acceso total sin restricciones al sistema, base de datos, sesiones, logs y variables de entorno.', 100, 'bg-amber-500/20 text-amber-300 border-amber-500/40', 'Acceso Total, Gestión de Rangos, Control de Usuarios, Revocar Sesiones, Logs de Auditoría, Acción Root', '2026-08-24T17:26:52.238941') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, label = EXCLUDED.label, description = EXCLUDED.description, level = EXCLUDED.level, badge_color = EXCLUDED.badge_color, permissions = EXCLUDED.permissions;
INSERT INTO roles (id, code, name, label, description, level, badge_color, permissions, created_at) VALUES (2, 'admin', 'ADMIN', 'Administrador CMS', 'Administración de contenido, moderación de productos, catálogos, banners y branding.', 50, 'bg-purple-500/20 text-purple-300 border-purple-500/40', 'Moderación de Productos, Gestión de Banners, Branding & CMS, Publicaciones', '2026-08-24T17:26:52.238941') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, label = EXCLUDED.label, description = EXCLUDED.description, level = EXCLUDED.level, badge_color = EXCLUDED.badge_color, permissions = EXCLUDED.permissions;
INSERT INTO roles (id, code, name, label, description, level, badge_color, permissions, created_at) VALUES (3, 'cliente', 'CLIENTE', 'Usuario Comprador / Vendedor', 'Perfil estándar de usuario para comprar, publicar productos C2C y gestionar billetera.', 10, 'bg-[#2a2a2a] text-[#8c8c8c] border-[#333333]', 'Comprar Productos, Publicar Venta C2C, Mi Billetera, Mi Perfil', '2026-08-24T17:26:52.239951') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, label = EXCLUDED.label, description = EXCLUDED.description, level = EXCLUDED.level, badge_color = EXCLUDED.badge_color, permissions = EXCLUDED.permissions;
INSERT INTO roles (id, code, name, label, description, level, badge_color, permissions, created_at) VALUES (4, 'solo_compras', 'SOLO COMPRAS', 'se permite solo comprar', 'Solo se le permitre comprar', 10, 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40', 'Personalizado', '2026-08-25T10:52:36.094153') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, label = EXCLUDED.label, description = EXCLUDED.description, level = EXCLUDED.level, badge_color = EXCLUDED.badge_color, permissions = EXCLUDED.permissions;

-- 3. TABLA PERMISSIONS
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (6, 'manage_products', 'Moderación de Productos', 'CMS', 'Aprobar, rechazar y revisar publicaciones', '2026-08-24T18:00:19.946824', NULL) ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (9, 'buy_products', 'Comprar Productos', 'Operaciones', 'Realizar compras en la plataforma', '2026-08-24T18:00:19.946824', NULL) ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (10, 'sell_products', 'Publicar Venta C2C', 'Operaciones', 'Crear anuncios y vender artículos', '2026-08-24T18:00:19.946824', NULL) ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (11, 'wallet_access', 'Mi Billetera', 'Operaciones', 'Gestionar ingresos y retirar saldos', '2026-08-24T18:00:19.946824', 'billetera') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (12, 'mi_perfil', 'Mi Perfil', 'Mi Espacio', '', '2026-08-25T18:20:16.336455', 'perfil') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (8, 'manage_branding', 'Apariencia Web', 'CMS', 'Modificar la interfaz y presentación pública', '2026-08-24T18:00:19.946824', 'appearance') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (7, 'manage_banners', 'Banners de inicio', 'CMS', 'Crear y editar sliders y marcas', '2026-08-24T18:00:19.946824', 'banners') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (13, 'personalizacion', 'Personalizacion', 'Gestión de Contenido', '', '2026-08-25T18:37:53.389611', 'secciones') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (14, 'campaña_y_eventos', 'Campaña y Eventos', 'Gestión de Contenido', '', '2026-08-25T18:38:44.187319', 'campanas') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (15, 'panel_de_control', 'Panel de Control', 'Sección Administrador', '', '2026-08-25T18:39:38.227931', 'dashboard') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (16, 'mis_publicaciones', 'Mis publicaciones', 'Mi Espacio', '', '2026-08-25T18:41:08.918911', 'publications') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (17, 'mis_compras', 'Mis Compras', 'Mi espacio', '', '2026-08-25T18:41:45.961559', 'purchases') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (18, 'mis_ventas', 'Mis Ventas', 'Mi espacio', '', '2026-08-25T18:42:13.303749', 'sales') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (19, 'control_de_permisos', 'Control de Permisos', 'Programador', '', '2026-08-25T18:43:18.645486', 'permissions') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (20, 'secciones_y_acciones', 'Secciones y Acciones', 'Programador', '', '2026-08-25T18:44:19.597080', 'sections') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (4, 'view_audit_logs', 'Registros y Auditoria', 'Programador', 'Consultar el historial de eventos del sistema', '2026-08-24T18:00:19.946824', 'logs') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (2, 'manage_roles', 'Control de Rangos', 'Programador', 'Crear, editar y eliminar rangos y permisos', '2026-08-24T18:00:19.946824', 'roles') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (3, 'manage_users', 'Control de Usuarios', 'Sistema', 'Ver usuarios, cambiar rangos y eliminar cuentas', '2026-08-24T18:00:19.946824', 'users') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (5, 'manage_sessions', 'Monitor de Sesiones', 'Programador', 'Ver sesiones activas e inactivar accesos remotamente', '2026-08-24T18:00:19.946824', 'sessions') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;
INSERT INTO permissions (id, code, name, category, description, created_at, target_section) VALUES (1, 'full_access', 'Acceso Total Root', 'Sistema', 'Supervisión total y configuración avanzada', '2026-08-24T18:00:19.946824', 'admin_section,dashboard,moderation,cms,appearance,campanas,secciones,banners,system,users,roles,permissions,sections,sessions,logs,mi_espacio,billetera,publications,purchases,sales,perfil') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, target_section = EXCLUDED.target_section;

-- 4. TABLA ROLE_PERMISSIONS
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (1, 4, 9, '2026-08-25T10:52:36.106942') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (2, 1, 1, '2026-08-25T17:41:22.584021') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (15, 2, 6, '2026-08-25T18:50:38.527304') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (16, 2, 16, '2026-08-25T18:50:38.527304') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (17, 2, 9, '2026-08-25T18:50:38.527304') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (18, 2, 10, '2026-08-25T18:50:38.527304') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (19, 2, 15, '2026-08-25T18:50:38.527304') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (20, 2, 8, '2026-08-25T18:50:38.527304') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (21, 2, 7, '2026-08-25T18:50:38.527304') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (22, 2, 14, '2026-08-25T18:50:38.527304') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (23, 2, 13, '2026-08-25T18:50:38.527304') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (24, 2, 17, '2026-08-25T18:50:38.527304') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (25, 2, 18, '2026-08-25T18:50:38.527304') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (26, 2, 12, '2026-08-25T18:50:38.527304') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (27, 2, 11, '2026-08-25T18:50:38.527304') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (28, 2, 3, '2026-08-25T18:50:38.527304') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (35, 3, 9, '2026-08-25T19:11:57.875004') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (36, 3, 11, '2026-08-25T19:11:57.875004') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (37, 3, 12, '2026-08-25T19:11:57.875004') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (38, 3, 10, '2026-08-25T19:11:57.875004') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (39, 3, 18, '2026-08-25T19:11:57.875004') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (40, 3, 16, '2026-08-25T19:11:57.875004') ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (id, role_id, permission_id, created_at) VALUES (41, 3, 17, '2026-08-25T19:11:57.875004') ON CONFLICT (id) DO NOTHING;

-- 5. TABLA APP_SECTIONS
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (2, 'root_console', 'Consola Programador Root', 'Sistema', '', 'system', 'Terminal', true, '2026-08-25T10:35:24.895154', NULL) ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (3, 'users_control', 'Control de Usuarios', 'Sistema', '', 'system', 'Users', true, '2026-08-25T10:35:24.895154', NULL) ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (4, 'roles_control', 'Control de Rangos', 'Sistema', '', 'system', 'Sliders', true, '2026-08-25T10:35:24.895154', NULL) ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (5, 'permissions_control', 'Control de Permisos', 'Sistema', '', 'system', 'Key', true, '2026-08-25T10:35:24.895154', NULL) ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (6, 'sections_control', 'Control de Secciones y Acciones', 'Sistema', '', 'system', 'FolderTree', true, '2026-08-25T10:35:24.895154', NULL) ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (7, 'sessions_monitor', 'Monitor de Sesiones', 'Sistema', '', 'system', 'Activity', true, '2026-08-25T10:35:24.895154', NULL) ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (8, 'audit_logs', 'Logs de Auditoría', 'Sistema', '', 'system', 'Database', true, '2026-08-25T10:35:24.902888', NULL) ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (10, 'admin_dashboard', 'Panel de Control Admin', 'CMS', '', 'cms', 'BarChart3', true, '2026-08-25T10:35:24.902888', NULL) ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (14, 'operations', 'Mercado y Operaciones C2C', 'Operaciones', '', NULL, 'ShoppingBag', true, '2026-08-25T10:35:24.902888', NULL) ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (1, 'system', 'Programador', 'Programador', '', NULL, 'Shield', true, '2026-08-25T10:35:24.895154', NULL) ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (9, 'cms', 'Gestión de Contenido', 'Gestión de Contenido', '', NULL, 'Layout', true, '2026-08-25T10:35:24.902888', NULL) ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (20, 'admin_section', 'Sección Administrador', 'Sección Administrador', '', NULL, 'Shield', true, '2026-08-25T17:04:15.513245', NULL) ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (11, 'appearance', 'Apariencia Web', 'Gestión de Contenido', '', 'cms', 'Palette', true, '2026-08-25T10:35:24.902888', '/appearance') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (12, 'banners', 'Banners de Inicio', 'Gestión de Contenido', '', 'cms', 'Image', true, '2026-08-25T10:35:24.902888', '/banners') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (13, 'moderation', 'Productos en Revisión', 'Sección Administrador', '', 'admin_section', 'CheckSquare', true, '2026-08-25T10:35:24.902888', '/moderation') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (21, 'dashboard', 'Panel de Control', 'Sección Administrador', '', 'admin_section', 'BarChart3', true, '2026-08-25T17:04:15.513245', '/dashboard') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (22, 'campanas', 'Campañas y Eventos', 'Gestión de Contenido', '', 'cms', 'Calendar', true, '2026-08-25T17:04:15.513245', '/campanas') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (23, 'secciones', 'Personalización', 'Gestión de Contenido', '', 'cms', 'Sliders', true, '2026-08-25T17:04:15.513245', '/secciones') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (24, 'users', 'Control de Usuarios', 'Programador', '', 'system', 'Users', true, '2026-08-25T17:04:15.513245', '/users') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (25, 'roles', 'Control de Rangos', 'Programador', '', 'system', 'Sliders', true, '2026-08-25T17:04:15.513245', '/roles') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (26, 'permissions', 'Control de Permisos', 'Programador', '', 'system', 'Key', true, '2026-08-25T17:04:15.514288', '/permissions') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (27, 'sections', 'Secciones y Acciones', 'Programador', '', 'system', 'FolderTree', true, '2026-08-25T17:04:15.514288', '/sections') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (28, 'sessions', 'Monitor de Sesiones', 'Programador', '', 'system', 'Activity', true, '2026-08-25T17:04:15.514288', '/sessions') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (29, 'logs', 'Registros y Auditoría', 'Programador', '', 'system', 'Database', true, '2026-08-25T17:04:15.514805', '/logs') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (15, 'billetera', 'Mi Billetera', 'Mi Espacio', '', 'mi_espacio', 'Wallet', true, '2026-08-25T10:35:24.902888', '/mi-espacio?tab=billetera') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (16, 'publications', 'Mis Publicaciones', 'Mi Espacio', '', 'mi_espacio', 'Tag', true, '2026-08-25T10:35:24.902888', '/mi-espacio?tab=publications') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (17, 'purchases', 'Mis Compras', 'Mi Espacio', '', 'mi_espacio', 'ShoppingBag', true, '2026-08-25T10:35:24.902888', '/mi-espacio?tab=purchases') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (18, 'sales', 'Mis Ventas', 'Mi Espacio', '', 'mi_espacio', 'DollarSign', true, '2026-08-25T10:35:24.902888', '/mi-espacio?tab=sales') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (30, 'mi_espacio', 'Mi Espacio', 'Mi Espacio', '', NULL, 'UserCheck', true, '2026-08-25T18:05:39.032462', NULL) ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;
INSERT INTO app_sections (id, code, name, category, description, parent_code, icon_name, is_active, created_at, path) VALUES (31, 'perfil', 'Mi Perfil', 'Mi Espacio', '', 'mi_espacio', 'User', true, '2026-08-25T18:05:39.033466', '/mi-espacio?tab=perfil') ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, parent_code = EXCLUDED.parent_code, icon_name = EXCLUDED.icon_name, is_active = EXCLUDED.is_active, path = EXCLUDED.path;

-- 6. TABLA SECTION_ACTIONS
INSERT INTO section_actions (id, section_code, code, name, description, is_active, created_at) VALUES (1, 'publications', 'sell_products', 'Publicar y Vender Artículos C2C', 'Permite crear y publicar productos para la venta', true, '2026-08-25T10:35:24.902888') ON CONFLICT (id) DO UPDATE SET section_code = EXCLUDED.section_code, code = EXCLUDED.code, name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active;
INSERT INTO section_actions (id, section_code, code, name, description, is_active, created_at) VALUES (2, 'purchases', 'buy_products', 'Comprar Artículos', 'Permite efectuar compras de productos en la plataforma', true, '2026-08-25T10:35:24.902888') ON CONFLICT (id) DO UPDATE SET section_code = EXCLUDED.section_code, code = EXCLUDED.code, name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active;
INSERT INTO section_actions (id, section_code, code, name, description, is_active, created_at) VALUES (3, 'billetera', 'withdraw_funds', 'Retirar Saldo de Billetera', 'Solicitud de transferencia o retiro de fondos', true, '2026-08-25T10:35:24.902888') ON CONFLICT (id) DO UPDATE SET section_code = EXCLUDED.section_code, code = EXCLUDED.code, name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active;
INSERT INTO section_actions (id, section_code, code, name, description, is_active, created_at) VALUES (4, 'banners', 'create_banner', 'Crear Banners Publicitarios', 'Alta de piezas publicitarias', true, '2026-08-25T10:35:24.902888') ON CONFLICT (id) DO UPDATE SET section_code = EXCLUDED.section_code, code = EXCLUDED.code, name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active;
INSERT INTO section_actions (id, section_code, code, name, description, is_active, created_at) VALUES (5, 'moderation', 'approve_product', 'Aprobar/Rechazar Publicación', 'Moderación activa de productos C2C', true, '2026-08-25T10:35:24.902888') ON CONFLICT (id) DO UPDATE SET section_code = EXCLUDED.section_code, code = EXCLUDED.code, name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active;
INSERT INTO section_actions (id, section_code, code, name, description, is_active, created_at) VALUES (6, 'users_control', 'delete_user', 'Eliminar Usuarios', 'Baja de cuentas de usuario', true, '2026-08-25T10:35:24.902888') ON CONFLICT (id) DO UPDATE SET section_code = EXCLUDED.section_code, code = EXCLUDED.code, name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active;
INSERT INTO section_actions (id, section_code, code, name, description, is_active, created_at) VALUES (7, 'users_control', 'change_user_role', 'Cambiar Rango de Usuario', 'Modificar asignación de roles', true, '2026-08-25T10:35:24.902888') ON CONFLICT (id) DO UPDATE SET section_code = EXCLUDED.section_code, code = EXCLUDED.code, name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active;
INSERT INTO section_actions (id, section_code, code, name, description, is_active, created_at) VALUES (9, 'dashboard', 'view_dashboard_kpis', 'Ver Métricas y KPIs', 'Acceso a estadísticas en tiempo real', true, '2026-08-25T17:04:15.521572') ON CONFLICT (id) DO UPDATE SET section_code = EXCLUDED.section_code, code = EXCLUDED.code, name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active;
INSERT INTO section_actions (id, section_code, code, name, description, is_active, created_at) VALUES (10, 'moderation', 'moderate_products', 'Aprobar/Rechazar Publicación', 'Moderación activa de productos C2C', true, '2026-08-25T17:04:15.521572') ON CONFLICT (id) DO UPDATE SET section_code = EXCLUDED.section_code, code = EXCLUDED.code, name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active;
INSERT INTO section_actions (id, section_code, code, name, description, is_active, created_at) VALUES (11, 'appearance', 'edit_branding', 'Editar Colores y Branding', 'Permite modificar paleta y logotipo', true, '2026-08-25T17:04:15.521572') ON CONFLICT (id) DO UPDATE SET section_code = EXCLUDED.section_code, code = EXCLUDED.code, name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active;
INSERT INTO section_actions (id, section_code, code, name, description, is_active, created_at) VALUES (12, 'campanas', 'create_campaign', 'Crear y Gestionar Campañas 360', 'Alta y baja de eventos comerciales', true, '2026-08-25T17:04:15.521572') ON CONFLICT (id) DO UPDATE SET section_code = EXCLUDED.section_code, code = EXCLUDED.code, name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active;
INSERT INTO section_actions (id, section_code, code, name, description, is_active, created_at) VALUES (13, 'secciones', 'reorder_sections', 'Reordenar y Activar Carruseles', 'Modificación de vitrinas de inicio', true, '2026-08-25T17:04:15.521572') ON CONFLICT (id) DO UPDATE SET section_code = EXCLUDED.section_code, code = EXCLUDED.code, name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active;
INSERT INTO section_actions (id, section_code, code, name, description, is_active, created_at) VALUES (14, 'roles', 'manage_roles', 'Crear y Editar Rangos', 'Gestión de roles y asignación de permisos', true, '2026-08-25T17:04:15.523314') ON CONFLICT (id) DO UPDATE SET section_code = EXCLUDED.section_code, code = EXCLUDED.code, name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active;
INSERT INTO section_actions (id, section_code, code, name, description, is_active, created_at) VALUES (15, 'permissions', 'manage_permissions', 'Crear y Editar Permisos', 'Definición de permisos por página', true, '2026-08-25T17:04:15.523314') ON CONFLICT (id) DO UPDATE SET section_code = EXCLUDED.section_code, code = EXCLUDED.code, name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active;
INSERT INTO section_actions (id, section_code, code, name, description, is_active, created_at) VALUES (16, 'sections', 'manage_sections', 'Gestionar Secciones y Acciones', 'Administración del árbol jerárquico', true, '2026-08-25T17:04:15.523314') ON CONFLICT (id) DO UPDATE SET section_code = EXCLUDED.section_code, code = EXCLUDED.code, name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active;
INSERT INTO section_actions (id, section_code, code, name, description, is_active, created_at) VALUES (17, 'sessions', 'revoke_session', 'Revocar Sesiones Activas', 'Cierre forzado de sesiones de usuario', true, '2026-08-25T17:04:15.523314') ON CONFLICT (id) DO UPDATE SET section_code = EXCLUDED.section_code, code = EXCLUDED.code, name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active;
INSERT INTO section_actions (id, section_code, code, name, description, is_active, created_at) VALUES (18, 'logs', 'view_audit_logs', 'Ver Logs de Auditoría', 'Historial de acciones y seguridad', true, '2026-08-25T17:04:15.523314') ON CONFLICT (id) DO UPDATE SET section_code = EXCLUDED.section_code, code = EXCLUDED.code, name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active;

-- 7. ACTUALIZAR SECUENCIAS SERIALES
SELECT setval(pg_get_serial_sequence('roles', 'id'), COALESCE((SELECT MAX(id) FROM roles), 1));
SELECT setval(pg_get_serial_sequence('permissions', 'id'), COALESCE((SELECT MAX(id) FROM permissions), 1));
SELECT setval(pg_get_serial_sequence('role_permissions', 'id'), COALESCE((SELECT MAX(id) FROM role_permissions), 1));
SELECT setval(pg_get_serial_sequence('app_sections', 'id'), COALESCE((SELECT MAX(id) FROM app_sections), 1));
SELECT setval(pg_get_serial_sequence('section_actions', 'id'), COALESCE((SELECT MAX(id) FROM section_actions), 1));

COMMIT;
